[target.'cfg(all(target_arch = "arm", target_os = "none"))']

runner = "probe-run --chip nRF9160_xxAA"

[build]
target = "thumbv8m.main-none-eabihf" # Cortex-M33 (with FPU)

[env]
DEFMT_LOG = "debug"

[alias]
rb = "run --bin"
rrb = "run --release --bin"
s = "size --bin app -- -B -x"
sr = "size --release --bin app -- -B -x"